# Generated by Django 2.2 on 2020-01-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv1name', models.CharField(default='Channel Name', max_length=300)),
                ('tv1link', models.CharField(default='TV Link', max_length=300)),
                ('tv1ylink', models.CharField(default='TV Link', max_length=300)),
                ('tv2name', models.CharField(default='Channel Name', max_length=300)),
                ('tv2link', models.CharField(default='TV Link', max_length=300)),
                ('tv2ylink', models.CharField(default='TV Link', max_length=300)),
                ('tv3name', models.CharField(default='Channel Name', max_length=300)),
                ('tv3link', models.CharField(default='TV Link', max_length=300)),
                ('tv3ylink', models.CharField(default='TV Link', max_length=300)),
                ('tv4name', models.CharField(default='Channel Name', max_length=300)),
                ('tv4link', models.CharField(default='TV Link', max_length=300)),
                ('tv4ylink', models.CharField(default='TV Link', max_length=300)),
                ('tv5name', models.CharField(default='Channel Name', max_length=300)),
                ('tv5link', models.CharField(default='TV Link', max_length=300)),
                ('tv5ylink', models.CharField(default='TV Link', max_length=300)),
            ],
        ),
    ]
